### ISSUE TITLE
Updating build status fails sometimes

### ISSUE THREAD

**Issue by tomdaley92** [Diesel-Net/drone-discord#24]
Noticed there was a build that never changed from `running` status

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/api/discord.py", line 421, in post_build_updated
    if previous_post.get('status') == status:
AttributeError: 'NoneType' object has no attribute 'get'
```
![gnome-shell-screenshot-4M6OD1](https://user-images.githubusercontent.com/12147036/144726026-9652efac-f8bd-4478-b334-e18e4d86a152.png)

**Comment by tomdaley92** [comment]
here are the [logs](https://elastic.diesel.net/s/kiwi-labs/goto/75d63a40b85382a42bcf1f4ffeb28d87) in elastic

**Comment by tomdaley92** [comment]
Happened again today, so omitting the database removals in the code was not the direct cause. I think I might be overthinking this one, but sounds like a race condition of the last few requests that come from drone. For example, the "success/failure" status update is received right before a "running" status update pertaining to the same build #
